### ISSUE TITLE
Type 'SimpleSpanProcessor' is not assignable to type 'SpanProcessor'

### ISSUE THREAD

**Issue by TroyDavidson** [MetinSeylan/Nestjs-OpenTelemetry#47]
I'm getting the following error.  I'm using the sample code from the README.  I believe it's version dependency conflicts.

```
Type 'SimpleSpanProcessor' is not assignable to type 'SpanProcessor'.
  Types of property 'onStart' are incompatible.
    Type '(_span: Span, _parentContext: Context) => void' is not assignable to type '(span: Span, parentContext: Context) => void'.
      Types of parameters '_span' and 'span' are incompatible.
        Property '_clock' is missing in type 'import("/<snip>/node_modules/@opentelemetry/sdk-trace-node/node_modules/@opentelemetry/sdk-trace-base/build/src/Span").Span' but required in type 'import("/<snip>r/node_modules/@opentelemetry/sdk-trace-base/build/src/Span").Span'.ts(2322)

Span.d.ts(29, 22): '_clock' is declared here.
```

This is the example code I'm using:
```
    OpenTelemetryModule.forRoot({
      spanProcessor: new SimpleSpanProcessor(
        new ZipkinExporter({
          url: 'your-zipkin-url',
        })
      ),
    }),
```

**Comment by izevg** [comment]
Confirming.

**Temporary solution**: rollback/lock the `@opentelemetry/sdk-trace-base` version on `1.0.1`, as per this lib `package-lock.json`
**Proper way**: update all the used `@opentelemetry/*` packages to the actual versions & fix the issues. (FYI: `sdk-trace-base` is on `v1.7.0` already, and contains A LOT of breaking changes in between versions)

@MetinSeylan could you please be so kind? 🙏🏻

**Comment by MetinSeylan** [comment]
Hey 🖖 fixed with new version, but keep in mind new version required nestjs 9

**Comment by codeprefect** [comment]
Hi @MetinSeylan,

This issue persists even on nestjs v9.
As a stop-gap for my work, I forked this repo, and updated all the dependencies, which appears to fix it for my case.
I currently have the package installed with
```
"dependencies": {
  ...
  @metinseylan/nestjs-opentelemetry": "https://github.com/codeprefect/Nestjs-OpenTelemetry#head=update-otel-deps",
  ...
}
```
Happy to rollback once we have it fixed here.

**Comment by murar8** [comment]
I can confirm the issue persists for me too.

**Comment by slaaavyn** [comment]
The problem is actual, please approve PR https://github.com/MetinSeylan/Nestjs-OpenTelemetry/pull/58

**Comment by amitzig** [comment]
Any update on this?

**Comment by valanto** [comment]
@MetinSeylan Any update on this? The issue persists on NestJS 9. Thanks!

**Comment by slaaavyn** [comment]
Solved my problems by using opentelemetry without this library. 
As an example I use https://github.com/polyflix/video/blob/5d81560edca81e2d49a406b3a62b130f6839baf3/src/main/config/tracing.config.ts

**Comment by murar8** [comment]
For anyone still having this issue a temporary solution is to lock the peer dependencies in your package.json to the same version as the library (notice the missing ^)
```json
  "dependencies": {
    "@metinseylan/nestjs-opentelemetry": "^3.0.0",
    "@opentelemetry/sdk-trace-base": "1.9.1"
  },
  ```
